baseURL = 'https://cancms.github.io/TangJingyu/'
languageCode = 'en-us'
title = 'TangJingyu'




############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true





